# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM gcr.io/deeplearning-platform-release/base-gpu.py310

RUN apt-get update

WORKDIR /root

#install sd libraries
RUN git clone --recurse-submodules https://github.com/Akegarasu/lora-scripts
WORKDIR lora-scripts
RUN git checkout 1a483a0fd9aa1257b0bb4cfe5314054564675121

WORKDIR /root
#install libraries
RUN pip install accelerate==0.18.0
RUN pip install xformers==0.0.18
RUN pip install safetensors==0.3.0
RUN pip install tqdm==4.65.0
RUN pip install ftfy==6.1.1
RUN pip install loralib==0.1.1
RUN pip install evaluate==0.4.0
RUN pip install psutil==5.9.4
RUN pip install PyYAML==6.0
RUN pip install packaging==23.0
RUN pip install transformers==4.27.4
RUN pip install bitsandbytes==0.35.0
RUN pip install diffusers[torch]==0.10.2
RUN pip install albumentations==1.3.0
RUN pip install opencv-python-headless==4.7.0.72
RUN pip install einops==0.6.0
RUN pip install pytorch-lightning==2.0.1
RUN pip install gradio==3.25.0
RUN pip install altair==4.2.2
RUN pip install easygui==0.98.3
RUN pip install toml==0.10.2
RUN pip install voluptuous==0.13.1
RUN pip install timm==0.6.13
RUN pip install fairscale==0.4.13
RUN pip install huggingface-hub==0.13.4
RUN pip install tensorflow==2.10.1 tensorboard==2.10.1
RUN pip install lion-pytorch==0.0.7
RUN pip install lycoris-lora==0.1.4
RUN pip install cloudml-hypertune==0.1.0.dev6
#install pytorch
RUN pip install torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118

# Copies the trainer code to the docker image.
COPY train_kohya.py /root/train_kohya.py

# Sets up the entry point to invoke the trainer.
#ENTRYPOINT ["python3", "-m", "train_kohya"]
