FROM nvidia/cuda:11.8.0-runtime-ubuntu22.04

RUN set -ex && \
    apt update && \
    apt install -y wget git python3 python3-venv python3-pip libglib2.0-0 pkg-config libcairo2-dev libxext6 libtcmalloc-minimal4 && \
    rm -rf /var/lib/apt/lists/*

ENV PATH="/root/miniconda3/bin:${PATH}"
ARG PATH="/root/miniconda3/bin:${PATH}"
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh \
    && echo "Running $(conda --version)" && \
    conda init bash && \
    . /root/.bashrc && \
    conda update conda && \
    conda install -y mamba -c conda-forge && \
    conda create -n sd-webui && \
    conda activate sd-webui && \
    conda install python=3.10 pip

RUN echo 'conda activate sd-webui' >> /root/.bashrc

RUN . /root/.bashrc \
    && python3 -m pip install torch torchvision --index-url https://download.pytorch.org/whl/cu118 --prefer-binary \
    && python3 -m pip install git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 --prefer-binary \
    && python3 -m pip install git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 --prefer-binary \
    && python3 -m pip install git+https://github.com/mlfoundations/open_clip.git@bb6e834e9c70d9c27d0dc3ecedeebeaeb1ffad6b --prefer-binary \
    && python3 -m pip install --pre xformers --prefer-binary \
    && python3 -m pip install pyngrok --prefer-binary \
    && git -C https://github.com/AUTOMATIC1111/stable-diffusion-webui.git checkout 89f9faa63388756314e8a1d96cf86bf5e0663045 \
    && git clone https://github.com/Stability-AI/stablediffusion.git /stable-diffusion-webui/repositories/stable-diffusion-stability-ai \
    && git -C /stable-diffusion-webui/repositories/stable-diffusion-stability-ai checkout cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf \
    && git clone https://github.com/CompVis/taming-transformers.git /stable-diffusion-webui/repositories/taming-transformers \
    && git -C /stable-diffusion-webui/repositories/taming-transformers checkout 24268930bf1dce879235a7fddd0b2355b84d7ea6 \
    && git clone https://github.com/crowsonkb/k-diffusion.git /stable-diffusion-webui/repositories/k-diffusion \
    && git -C /stable-diffusion-webui/repositories/k-diffusion checkout c9fe758757e022f05ca5a53fa8fac28889e4f1cf \
    && git clone https://github.com/sczhou/CodeFormer.git /stable-diffusion-webui/repositories/CodeFormer \
    && git -C /stable-diffusion-webui/repositories/CodeFormer checkout c5b4593074ba6214284d6acd5f1719b6c5d739af \
    && git clone https://github.com/salesforce/BLIP.git /stable-diffusion-webui/repositories/BLIP \
    && git -C /stable-diffusion-webui/repositories/BLIP checkout 48211a1594f1321b00f14c9f7a5b4813144b2fb9 \
    && python3 -m pip install -r /stable-diffusion-webui/repositories/CodeFormer/requirements.txt --prefer-binary \
    && python3 -m pip install -r /stable-diffusion-webui/requirements_versions.txt --prefer-binary

RUN set -ex && cd stable-diffusion-webui \
    && git clone https://github.com/kohya-ss/sd-webui-additional-networks.git extensions/sd-webui-additional-networks \
    && git clone https://github.com/hnmr293/sd-webui-cutoff.git extensions/sd-webui-cutoff \
    && git clone https://github.com/toriato/stable-diffusion-webui-wd14-tagger.git extensions/stable-diffusion-webui-wd14-tagger \
    && git clone https://github.com/DominikDoom/a1111-sd-webui-tagcomplete.git extensions/a1111-sd-webui-tagcomplete \
    && git clone https://github.com/Mikubill/sd-webui-controlnet.git extensions/sd-webui-controlnet \
    && git -C https://github.com/zanllp/sd-webui-infinite-image-browsing.git extensions/sd-webui-infinite-image-browsing checkout 4720b15126c3ee05e97d50108050d1178e50639b \
    && git clone https://github.com/aria1th/Hypernetwork-MonkeyPatch-Extension.git extensions/Hypernetwork-MonkeyPatch-Extension \
    && git clone https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper.git extensions/Stable-Diffusion-Webui-Civitai-Helper \
    && git clone https://github.com/ilian6806/stable-diffusion-webui-state.git extensions/stable-diffusion-webui-state \
    && git clone https://github.com/vladmandic/sd-extension-system-info extensions/sd-extension-system-info \
    && git clone https://github.com/ArtVentureX/sd-webui-agent-scheduler.git extensions/agent-scheduler

RUN . /root/.bashrc \
    && python3 -m pip install -r /stable-diffusion-webui/extensions/sd-webui-controlnet/requirements.txt --prefer-binary

COPY extensions/ /stable-diffusion-webui/extensions/
COPY user-watch.py /stable-diffusion-webui/user-watch.py
COPY start.sh /stable-diffusion-webui/start.sh
COPY *.json /stable-diffusion-webui/

ENV SAFETENSORS_FAST_GPU=1
ENV LD_PRELOAD="/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so.4"

EXPOSE 7860

WORKDIR /stable-diffusion-webui/
CMD ["conda", "run", "--no-capture-output", "-n", "sd-webui", "python3", "launch.py", "--listen", "--xformers", "--medvram", "--enable-insecure-extension-access"]